### ISSUE TITLE
图片放大后后, 在普通1x屏幕下图片模糊

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.org#12]
mobile适配时, 为了适配@2x屏, 把不少图片的尺寸放大, 但放大后, 在普通1x屏幕下图片会变模糊.
包括
* logo.png
* feature-icon/*.png

请做如下改动:
- [ ] 恢复原尺寸图片
- [ ] 将2x屏下的图片名称统一改为foo@2x.png, 例如logo.png改为logo@2x.png
- [ ] 在less中判断当前的pixelRatio的值, 为2时载入foo@2x.png, 否则载入原尺寸foo.png

**Comment by k111ua** [comment]
已修改
