### ISSUE TITLE
Documentation鼠标移动到空白区域时, drop-menu会出现

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.org#16]
![image](https://user-images.githubusercontent.com/13678919/28491205-7af84822-6f1f-11e7-9023-39671229d061.png)
如图所示, 鼠标移到箭头所在地方, documentation的drop-menu会弹出来

在移动端上, 隐藏时的drop-menu会挡住一些链接, 造成链接无法点击

请改为鼠标移动到documentation链接上时再弹出, 隐藏时也不会遮住其他内容

可访问[maptalks.org](https://maptalks.org)查看问题

**Comment by k111ua** [comment]
已修改
