### ISSUE TITLE
栏目导航栏在屏幕较小时改成按钮菜单形式

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.org#18]
目前:
![image](https://user-images.githubusercontent.com/13678919/28763128-56ca1b94-75ee-11e7-9efd-d603d638005d.png)

改成, 参考[mapbox](https://mapbox.com):

![image](https://user-images.githubusercontent.com/13678919/28763145-67ebfac8-75ee-11e7-8a5d-efcc4fb853e7.png)

**Comment by k111ua** [comment]
已修改
