### ISSUE TITLE
首页的三个Feature图片比例不是很好

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.org#19]
三个图片在不同分辨率下, 比例不是很统一, 看上去效果不是很好, 请帮忙看看怎么调整的比例比较一致

比如宽度1280时, 三个图片的高宽都很不一致

请调整一下css, 并指导一下三个图片都做成怎样的比例, 它们三者在不同的分辨率下都能比较一致

如有必要, 可以修改图片设计, 比如从圆形变为矩形.

**Comment by k111ua** [comment]
已修改，配图轮廓都改成了矩形，各分辨率下比例保持一致
