### ISSUE TITLE
maptalks-echarts-gl

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.org#27]
> Submit a plugin or a gallery example?

> URL

https://gitee.com/iverson_hu/maptalks-echarts-gl

> Any comments?

ehcarts-gl 添加 maptalks支持

@fuzhenn  这个更像是echarts-gl 的插件啊，可以叫@pissang 合并到 echarts-gl 里

**Comment by fuzhenn** [comment]
赞！

**Comment by pissang** [comment]
@deyihu 赞！！其实之前就有开发一个 maptalks 插件的想法，可以给 GL 提个 PR？这样可以在GL 的 contributors 里有个你的记录，如果不方便的话我就手动合吧

**Comment by fuzhenn** [comment]
closed by https://github.com/ecomfe/echarts-gl/commit/8a83d6211a50148e442afcbc41b4d7c347406616
