### ISSUE TITLE
a  maptalks  visualization  demo

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.org#28]
> Submit a plugin or a gallery example?
is a application  @fuzhenn 

> URL
 [repositorie](https://gitee.com/iverson_hu/maptalks-visual)

[exmaple](http://58.210.98.62:7080/maptalks.visual/)

> Any comments?
a  maptalks  visualization  demo

**Comment by fuzhenn** [comment]
哈哈，谢谢提交，这个地址稳定不？

**Comment by fuzhenn** [comment]
这个效果做的还真是酷炫吊炸天 👍

**Comment by deyihu** [comment]
@fuzhenn  http://120.26.224.171/maptalks.visual/ 这个地址比较稳定
