### ISSUE TITLE
webgl heatmap on maptalks

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.org#29]
> Submit a plugin or a gallery example?

is plugin @fuzhenn 

> URL
[ repository](https://gitee.com/iverson_hu/maptalks-WebglHeatLayer)
[example](http://120.26.224.171/maptalks-WebglHeatLayer/examples/test.html)

> Any comments?

**Comment by fuzhenn** [comment]
哈哈！ 谢谢！
过段时间我会集中更新到网站上

**Comment by zhangfan321** [comment]
你好，我用maptalks.e4引入echart-gl做了一个在地图上能用三维柱状图来表示热力图的方式，网上的用arcgis发布的底图是可以显示的，但是加上自己这边发布的底图就不能显示，而且就是缩放旋转也有问题了，网上的底图范围大是全世界的，自己这边发布的底图是某个市的，会不会是因为范围问题导致的，还是因为自己发布的底图的其他问题不支持三维显示？

**Comment by fuzhenn** [comment]
嗨，@zhangfan321
可能是因为echarts-gl目前还不支持3857之外的地图投影，所以需要先保证你自己发布的底图是3857投影，才能正常显示。

**Comment by zhangfan321** [comment]
不过我用网上发布的投影就是4326的都有效果呢，自己发布的投影也是4326，感觉不是投影的问题，我还是觉得是会不会是底图范围的问题呢

**Comment by fuzhenn** [comment]
哈哈，具体可以请教一下黄老师 @axmand
