### ISSUE TITLE
is Visualization lib on maptalks

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.org#30]
> Submit a plugin or a gallery example?
     is plugin  @fuzhenn 

Visualization of geographic data

this is inspire from [mapv](https://github.com/huiyan-fe/mapv)

> URL

[repository](https://gitee.com/iverson_hu/maptalks-gmvi)

[examples](http://120.26.224.171/maptalks-gmvi/examples/)

> Any comments?

**Comment by fuzhenn** [comment]
哇，太厉害了！ 哈哈！ @deyihu

**Comment by fuzhenn** [comment]
是否考虑把项目迁移一份到github上，然后部署在github pages里？
服务稳定一些，也方便全世界的人看到

**Comment by deyihu** [comment]
@fuzhenn   https://deyihu.github.io/
