### ISSUE TITLE
A maptalks.js plugin to load tilesets in .mbtiles format.

### ISSUE THREAD

**Issue by deyihu** [maptalks/maptalks.org#33]
> Submit a plugin or a gallery example?

is plugin

> URL

[Res](https://github.com/deyihu/maptalks-MBTileLayer)

[Example](https://deyihu.github.io/src/maptalks-MBTileLayer/examples/)

> Any comments?

**Comment by deyihu** [comment]
@fuzhenn   这个网络给跪了
![2018-03-17 23-42-07](https://user-images.githubusercontent.com/25998927/37557272-f9072a34-2a3c-11e8-8768-57283d76b1f7.png)

**Comment by fuzhenn** [comment]
赞~ 
网站维护起来太费劲，我打算做一个maptalks的awesome list，把你给我的插件都挪到那里去
https://github.com/maptalks/awesome-maptalks
