### ISSUE TITLE
plugins.html中显示插件作者昵称

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/maptalks.org#6]
现在的设计是鼠标停在插件上, 才显示作者昵称.

改成在插件上直接显示作者昵称

**Comment by k111ua** [comment]
已修改

**Comment by fuzhenn** [comment]
👍 
不过代码还没看到, 请push一下

**Comment by fuzhenn** [comment]
哦, 看到了, 在你的分支里
github有个隐藏功能, 可以考虑用一下
你可以在git的Commit message里带上issue编号, issue里能实时显示那个commit链接
例如
`fix #6, 在plugin中显示插件作者昵称`

**Comment by fuzhenn** [comment]
@k111ua

**Comment by k111ua** [comment]
好的，get到了
